[package]
name = "GPIO"
version = "0.1.0"
edition = "2021"

[profile.release]
panic = "abort"
opt-level = "z"

[profile.dev]
opt-level = "z"

[dependencies]
cortex-m = "0.6.0"
cortex-m-rt = "0.6.10"
cortex-m-semihosting = "0.3.3"
panic-halt = "0.2.0"